const baseUrl = process.env.REACT_APP_API_ENDPOINT!;

export const sellers = baseUrl + 'sellers/';
export const totalContributions = baseUrl + 'sellers/total_contributions';
export const charges = baseUrl + 'charges';
export const vouchers = baseUrl + 'gift_cards/';
export const vouchers20Count = vouchers + '?items=20&page=';
export const vouchersMetadata = vouchers + 'metadata';
export const campaigns = baseUrl + 'campaigns/';
export const fees = baseUrl + 'fees/';
export const distributors = baseUrl + 'distributors/';
export const nonprofits = baseUrl + 'nonprofits/';
export const passportVouchers = baseUrl + 'participating_sellers/';
export const contacts = baseUrl + 'contacts/';
export const tickets = baseUrl + 'tickets/';
export const participatingSellers = baseUrl + 'participating_sellers/';
export const sponsorSellers = baseUrl + 'sponsor_sellers/';
export const locations = baseUrl + 'locations/';
export const lyftRewards = 'lyft_rewards/';
export const projects = baseUrl + 'projects/';
export const gcs = baseUrl + 'gcs/';
export const crawlReceipts = baseUrl + 'crawl_receipts/';
export const crawlRewards = baseUrl + 'rewards/';
export const crawlRedemptions = baseUrl + 'redemptions/';
export const authGoogle = baseUrl + 'auth/google';
export const authPasswordless = baseUrl + 'auth/passwordless';
export const authValidate = baseUrl + 'auth/validate';
