/**
 *
 * TYPE constants for Card Details Context
 *
 *
 */
const SET_MODAL_VIEW = 'SET_MODAL_VIEW';
const SET_AMOUNT = 'SET_AMOUNT';
const CLOSE_MODAL = 'CLOSE_MODAL';
const CLEAR_FORMS = 'CLEAR_FORMS';

const SET_SELLER_DATA = 'SET_SELLER_DATA';
const UPDATE_SELLER_DATA = 'UPDATE_SELLER_DATA';

const EMAIL_REGEX = /[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}$/;

const TRANSACTION_FEE_PERCENT = 0.03;
const CUSTOM_AMOUNT_MIN = 5;
const CUSTOM_AMOUNT_MAX = 10000;

export {
  SET_MODAL_VIEW,
  SET_AMOUNT,
  CLOSE_MODAL,
  CLEAR_FORMS,
  SET_SELLER_DATA,
  UPDATE_SELLER_DATA,
  EMAIL_REGEX,
  TRANSACTION_FEE_PERCENT,
  CUSTOM_AMOUNT_MIN,
  CUSTOM_AMOUNT_MAX
};
