/**
 *
 * TYPE constants for Card Details Context
 *
 *
 */
const SET_MODAL_VIEW = 'SET_MODAL_VIEW';
const SET_AMOUNT = 'SET_AMOUNT';
const SET_CUSTOM_INPUT = 'SET_CUSTOM_INPUT';
const SET_COVERED_BY_CUSTOMER = 'SET_COVERED_BY_CUSTOMER';
const CLOSE_MODAL = 'CLOSE_MODAL';
const CLEAR_FORMS = 'CLEAR_FORMS';

const SET_SELLER_DATA = 'SET_SELLER_DATA';
const UPDATE_SELLER_DATA = 'UPDATE_SELLER_DATA';

const EMAIL_REGEX = /[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}$/;

const TRANSACTION_FEE_RATE = 0.029;
const TRANSACTION_FEE_FLAT = 30;

export {
  SET_MODAL_VIEW,
  SET_AMOUNT,
  SET_CUSTOM_INPUT,
  SET_COVERED_BY_CUSTOMER,
  CLOSE_MODAL,
  CLEAR_FORMS,
  EMAIL_REGEX,
  SET_SELLER_DATA,
  UPDATE_SELLER_DATA,
  TRANSACTION_FEE_RATE,
  TRANSACTION_FEE_FLAT
};
